export * from './app/cocktail-configurator.module'
export { Cocktail, CocktailLayer, CocktailComponent } from './app/model/cocktail'
export { BeakerComponent } from './app/beaker/beaker.component'
export { ComponentListComponent } from './app/component-list/component-list.component'
export { ComponentListDialogComponent } from './app/component-list-dialog/component-list-dialog.component'
export { IngredientsListingComponent } from './app/ingredients-listing/ingredients-listing.component'
export { DragAndDropService } from './app/services/drag-and-drop.service'
export { ComponentService } from './app/services/component.service'
// export { CocktailConfiguratorModule } from './src/app/cocktail-configurator.module'
// export { Cocktail } from './src/app/model/cocktail'